const express=require('express');const multer=require('multer');const QRCode=require('qrcode');const crypto=require('crypto');const fs=require('fs');const path=require('path');const os=require('os');
const app=express(),PORT=Number(process.env.PORT||8787),desktop=path.join(os.homedir(),'Desktop'),sessions=new Map();
const upload=multer({dest:path.join(os.tmpdir(),'phone-transfer-uploads'),limits:{fileSize:10*1024*1024*1024,files:100}});
app.use(express.static(path.join(__dirname,'public')));
app.get('/api/session',(req,res)=>{const token=crypto.randomBytes(18).toString('base64url');sessions.set(token,{createdAt:Date.now(),files:[]});setTimeout(()=>sessions.delete(token),30*60*1000);res.json({token,uploadUrl:`http://${lanAddress()}:${PORT}/upload.html?token=${encodeURIComponent(token)}`})});
app.get('/api/session/:token',(req,res)=>{const s=sessions.get(req.params.token);if(!s)return res.status(404).json({error:'二维码已过期，请重新生成'});res.json({files:s.files})});
app.get('/api/qr',async(req,res)=>{if(!req.query.text)return res.status(400).end();try{res.type('png').send(await QRCode.toBuffer(String(req.query.text),{width:320,margin:2}))}catch{res.status(400).end()}});
app.post('/api/upload/:token',upload.array('files'),(req,res)=>{const s=sessions.get(req.params.token);if(!s)return res.status(404).json({error:'二维码已过期，请重新生成'});fs.mkdirSync(desktop,{recursive:true});const saved=[];for(const file of req.files||[]){const safe=path.basename(file.originalname).replace(/[\\/:*?"<>|\0]/g,'_')||`upload-${Date.now()}`;let target=path.join(desktop,safe);if(fs.existsSync(target)){const ext=path.extname(safe),stem=path.basename(safe,ext);target=path.join(desktop,`${stem}-${Date.now()}${ext}`)}fs.renameSync(file.path,target);const item={name:path.basename(target),size:file.size,time:new Date().toISOString()};s.files.push(item);saved.push(item)}res.json({files:saved})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>{console.log(`电脑端页面: http://localhost:${PORT}/desktop.html`);console.log(`文件保存目录: ${desktop}`)});function lanAddress(){for(const list of Object.values(os.networkInterfaces()))for(const info of list||[])if(info.family==='IPv4'&&!info.internal)return info.address;return'localhost'}
